spring.cloud.consul.host=consul
spring.cloud.consul.port=8500

spring.kafka.bootstrap-servers=kafka:9092

spring.datasource.url=jdbc:postgresql://postgres-api:5432/notify_api_db
spring.datasource.username=postgres
spring.datasource.password=root