spring.application.name=api-gateway
server.port=8080

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.heartbeat.enabled=true
spring.cloud.consul.discovery.heartbeat.ttl-value=30s
spring.cloud.gateway.enabled=true
spring.cloud.gateway.server.webflux.routes[0].id=notify-api-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://notify-api
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/notify/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true
management.endpoint.health.show-details=always