name: Check
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: mvn clean compile test -Pprod -T 1C

  build:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker deploy
        run: |
          cat > .env << EOF
          POSTGRES_USER=${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
          API_DB=${{secrets.API_DB}}
          PROCESS_DB=${{secrets.PROCESS_DB}}
          SMSRU_API_KEY=${{secrets.SMSRU_API_KEY}}
          UNISENDER_API_KEY=${{secrets.UNISENDER_API_KEY}}
          ADMIN_API_KEY=${{secrets.ADMIN_API_KEY}}
          EOF
          docker compose up -d --build